---
# tasks file for nginx
- name: install nginx
  package: name=nginx state=present 
  become: yes

- name: Modify conf
  template: src="nginx.conf.j2" dest="/etc/nginx/nginx.conf"
  become: yes

- name: Modify http conf
  template: src="http.conf.j2" dest="/etc/nginx/sites-enabled/http.conf"
  become: yes

- name: Modify ssl conf
  template: src="ssl.conf.j2" dest="/etc/nginx/sites-enabled/ssl.conf"
  become: yes

- name: Remove default site
  file: state=absent dest="/etc/nginx/sites-enabled/default"
  become: yes